// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package golive

import (
	"github.com/ao-concepts/logging"
	"github.com/ao-concepts/storage"
	"github.com/jesko-plitt/golive/db"
	"github.com/jesko-plitt/golive/log"
	"github.com/jesko-plitt/golive/server"
	"io"
)

// Injectors from wire.go:

func InitializeLogger() logging.Logger {
	level := log.ProvideLevel()
	writer := _wireWriterValue
	logger := logging.New(level, writer)
	return logger
}

var (
	_wireWriterValue = (io.Writer)(nil)
)

func InitializeDatabase(log2 logging.Logger) *storage.Controller {
	dialector := db.ProvideDialector()
	config := db.ProvideConfig()
	controller := db.ProvideDB(dialector, config, log2)
	return controller
}

func InitializeServer() *Server {
	config := server.ProvideConfig()
	level := log.ProvideLevel()
	writer := _wireIoWriterValue
	logger := logging.New(level, writer)
	app := server.ProvideRouter(config, logger)
	shutdownService := server.ProvideShutdownService(logger)
	dialector := db.ProvideDialector()
	storageConfig := db.ProvideConfig()
	controller := db.ProvideDB(dialector, storageConfig, logger)
	goliveServer := provideServer(config, app, shutdownService, logger, controller)
	return goliveServer
}

var (
	_wireIoWriterValue = (io.Writer)(nil)
)
